name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!package.json' # Include all files except package.json

jobs:
  build:
    if: "github.event.head_commit.message != 'Prepare for version patch [skip ci]'" # Skip if the commit message indicates it's a version patch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: npm install

      - name: Run sd.config.mjs
        run: node sd.config.mjs

      - name: Build Storybook
        run: npm run build-storybook

      - name: Set git user
        run: |
          git config --global user.name "leoopardo"
          git config --global user.email "leo.san9@hotmail.com"

      - name: npm patch
        run: |
          git add .
          git commit -m "Prepare for version patch [skip ci]"
          npm run patch

      - name: Push changes
        run: git push

      - name: npm publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{
