name: Build

on:
  push:
    paths-ignore:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0  # This fetches all commits

      - name: Check for changes in package.json
        run: |
          git diff --quiet HEAD^ HEAD -- package.json && echo "No changes in package.json" || exit 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: npm install

      - name: Run sd.config.mjs
        run: node sd.config.mjs

      - name: Build Storybook
        run: npm run build-storybook

      - name: Set git user
        run: |
          git config --global user.name "leoopardo"
          git config --global user.email "leo.san9@hotmail.com"

      - name: npm patch
        run: |
          git add .
          git commit -m "Prepare for version patch"
          npm run patch

      - name: Push changes
        run: git push

      - name: npm publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm run deploy