name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run sd.config.mjs
      run: node sd.config.mjs

    - name: Build Storybook
      run: npm run build-storybook

    - name: npm publish
      run: npm run deploy
