  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11'

    - name: Install dependencies
      run: npm install

    - name: Stash changes
      run: git stash --include-untracked

    - name: Build Storybook
      run: npm run build-storybook

    - name: npm patch
      run: npm run patch

    - name: npm publish
      run: npm run deploy