name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!package.json' # Include all files except package.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11'

      - name: Install dependencies
        run: npm install

      - name: Run sd.config.mjs
        run: node sd.config.mjs

      - name: Build Storybook
        run: npm run build-storybook

      - name: Set git user
        run: |
          git config --global user.name "leoopardo"
          git config --global user.email "leo.san9@hotmail.com"

      - name: Check if commit is from workflow
        id: check_commit
        run: echo ::set-output name=is_workflow_commit::$(git log -1 --pretty=%B | grep -c "workflow")

      - name: Commit changes if not from workflow
        if: steps.check_commit.outputs.is_workflow_commit == '0'
        run: |
          git add .
          git commit -m "Prepare for version patch [skip ci]"
          git push

      - name: npm publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm run deploy
